import { NextRequest, NextResponse } from "next/server";

import { requireActiveAppUser } from "@/lib/adminAuthGuard";
import { ensureMysqlSchema, getMysqlPool, json } from "@/lib/mysql";
import { upsertSourceConfigRecord } from "@/lib/sourceConfigsDb";
import type { SourceConfig } from "@/lib/sourceConfig";

export const dynamic = "force-dynamic";

const GITHUB_REPO = process.env.GITHUB_REPO ?? "2024frank/ai-microgrant";
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

async function githubPut(filePath: string, rawContent: string, message: string): Promise<{ committed: boolean; url?: string; error?: string }> {
  if (!GITHUB_TOKEN) return { committed: false, error: "GITHUB_TOKEN not set" };

  const apiUrl = `https://api.github.com/repos/${GITHUB_REPO}/contents/${filePath}`;
  const content = Buffer.from(rawContent).toString("base64");

  let existingSha: string | undefined;
  try {
    const check = await fetch(apiUrl, {
      headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, Accept: "application/vnd.github+json" },
    });
    if (check.ok) {
      const existing = await check.json() as { sha: string };
      existingSha = existing.sha;
    }
  } catch { /* new file */ }

  const body: Record<string, string> = { message, content, branch: "main" };
  if (existingSha) body.sha = existingSha;

  const res = await fetch(apiUrl, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.text();
    return { committed: false, error: `GitHub ${res.status}: ${err.slice(0, 200)}` };
  }

  const data = await res.json() as { content: { html_url: string } };
  return { committed: true, url: data.content?.html_url };
}

export async function POST(req: NextRequest) {
  const guard = await requireActiveAppUser(req.headers.get("authorization"), "admin");
  if (!guard.ok) return guard.response;

  const { config, sourceCode } = await req.json();
  if (!config?.id || !config?.name) {
    return NextResponse.json({ error: "Config with id and name required" }, { status: 400 });
  }

  const sc = config as SourceConfig;

  // For custom_code sources, store the code in the config
  if (sc.type === "custom_code" && sourceCode) {
    sc.sourceCode = sourceCode;
  }

  const now = Date.now();
  await upsertSourceConfigRecord({
    ...sc,
    enabled: true,
    createdAt: sc.createdAt ?? now,
    updatedAt: now,
  } as SourceConfig & Record<string, unknown>);

  const sourceRow = {
    id: sc.id,
    name: sc.name,
    description: sc.description ?? "",
    type: sc.type,
    baseUrl: sc.url ?? "",
    schedule: sc.schedule ?? "off",
    scheduleHour: sc.scheduleHour ?? 6,
    lastRun: null as number | null,
    nextRun: null as number | null,
    createdAt: now,
    enabled: true,
  };

  await ensureMysqlSchema();
  await getMysqlPool().execute(
    `INSERT INTO sources (id, data) VALUES (?, CAST(? AS JSON))
     ON DUPLICATE KEY UPDATE data = VALUES(data)`,
    [sc.id, json(sourceRow)]
  );

  const githubResults: { config?: { committed: boolean; url?: string; error?: string }; code?: { committed: boolean; url?: string; error?: string } } = {};

  // Commit JSON config
  githubResults.config = await githubPut(
    `src/data/sourceConfigs/${sc.id}.json`,
    JSON.stringify({ ...sc, sourceCode: undefined }, null, 2) + "\n",
    `feat(sources): add ${sc.name} source config [Source Builder]`
  );

  // For custom_code: also commit the .ts fetcher file
  if (sc.type === "custom_code" && sourceCode) {
    const tsContent = `// Auto-generated by Source Builder AI — ${sc.name}
// Source ID: ${sc.id}
// This file is executed by the pipeline for custom event fetching.
// Available globals: fetch, URL, URLSearchParams, JSON, Date, maxEvents
// Must return: NormalizedEvent[]

import type { NormalizedEvent } from "@/lib/sourceConfig";

export const sourceCode = \`
${sourceCode.replace(/`/g, "\\`")}
\`;
`;
    githubResults.code = await githubPut(
      `src/data/customSources/${sc.id}.ts`,
      tsContent,
      `feat(sources): add ${sc.name} custom fetcher [Source Builder]`
    );
  }

  return NextResponse.json({ success: true, id: sc.id, github: githubResults });
}
